### ISSUE TITLE
Impossible to compile with gcc 14

### ISSUE THREAD

**Issue by vigna** [lorenzhs/BuRR#2]
I am trying to compile the benchmarks following the instructions, but I just get thousands of errors from g++ 14 on Linux Fedora. I guess it is some change in the C++ standard. There's also an inclusion of `xxhash.h` in `config.hpp` that does not work, but I think I fixed it with a symlink.

Could you have a look at the  [compiler.log](https://github.com/user-attachments/files/19045069/compiler.log) and suggest a workaround? Thanks!

**Comment by ByteHamster** [comment]
Apparently there are a bunch of new warnings in g++14 and BuRR has `-Wall` set. If you remove `-Werror` from the Makefile, it should work. In case you are interested, I have a simple wrapper around BuRR that supports cmake and manages the dependencies like xxhash: https://github.com/ByteHamster/SimpleRibbon

**Comment by ByteHamster** [comment]
I just fixed the warnings and added a CI check with different compilers

**Comment by vigna** [comment]
Still missing is the header:
```
In file included from backsubst.hpp:8,
                 from ribbon.hpp:7,
                 from ribbon.cpp:5:
config.hpp:17:10: fatal error: xxhash.h: No such file or directory
   17 | #include <xxhash.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: ribbon] Error 1
```

I think it would be good for people trying to use the code to document `RIBBON_BITS`. I had to discover by browsing through the source that I had to set that at compile time to select the precision of the filter.

**Comment by ByteHamster** [comment]
The code currently assumes that you have that library on your system (something like `apt install libxxhash-dev`). My SimpleRibbon wrapper ships a copy of the library to make installation easier.

**Comment by vigna** [comment]
Ah ok—solved. I tried a bit SimpleRibbon but there isn't a single line of documentation. :) I'll try to make this ribbon benchmarks work for me first, and then I'll see. Thanks!

**Comment by vigna** [comment]
BTW, also this version requires removing -Werror with gcc 14:
```
    inlined from ‘dysect::cuckoo_base<SCuckoo>::insert_return_type dysect::cuckoo_base<SCuckoo>::insert(const value_intern&) [with SCuckoo = dysect::cuckoo_standard<unsigned int, unsigned int, ribbon::{anonymous}::dysect_xxh3, dysect::cuckoo_config<4, 2> >]’ at DySECT/include/cuckoo_base.h:322:27:
thresh_compress.hpp:139:27: error: ‘local’ may be used uninitialized [-Werror=maybe-uninitialized]
  139 |         return XXH3_64bits(&local, sizeof(local));
      |                           ^
```

**Comment by ByteHamster** [comment]
Weird, we had the same warning in a similar-looking line in a completely different project. In both cases, the variable is definitely initialized. Makes me wonder if it is a problem in XXHash
